/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.5.1.0
 */
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace LexParserLib
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	[GeneratedCodeAttribute("Hime.SDK", "3.5.1.0")]
	internal class GrammarLexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(GrammarLexer), "GrammarLexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.1.0")]
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal id
			/// </summary>
			public const int TerminalId = 0x0003;
			/// <summary>
			/// The unique identifier for terminal realNumber
			/// </summary>
			public const int TerminalRealNumber = 0x0004;
			/// <summary>
			/// The unique identifier for terminal integerNumber
			/// </summary>
			public const int TerminalIntegerNumber = 0x0005;
			/// <summary>
			/// The unique identifier for terminal stringLiteral
			/// </summary>
			public const int TerminalStringLiteral = 0x0006;
			/// <summary>
			/// The unique identifier for terminal NEW_LINE
			/// </summary>
			public const int TerminalNewLine = 0x0007;
			/// <summary>
			/// The unique identifier for terminal WHITE_SPACE
			/// </summary>
			public const int TerminalWhiteSpace = 0x0008;
			/// <summary>
			/// The unique identifier for terminal COMMENT_LINE
			/// </summary>
			public const int TerminalCommentLine = 0x0009;
			/// <summary>
			/// The unique identifier for terminal SEPARATOR
			/// </summary>
			public const int TerminalSeparator = 0x000A;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.1.0")]
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0003, "id"),
			new Symbol(0x0004, "realNumber"),
			new Symbol(0x0005, "integerNumber"),
			new Symbol(0x0006, "stringLiteral"),
			new Symbol(0x0007, "NEW_LINE"),
			new Symbol(0x0008, "WHITE_SPACE"),
			new Symbol(0x0009, "COMMENT_LINE"),
			new Symbol(0x000A, "SEPARATOR"),
			new Symbol(0x0027, "export"),
			new Symbol(0x0028, "{"),
			new Symbol(0x0029, "}"),
			new Symbol(0x002A, "="),
			new Symbol(0x002B, "|"),
			new Symbol(0x002C, ","),
			new Symbol(0x002D, "_"),
			new Symbol(0x002E, "["),
			new Symbol(0x002F, "]"),
			new Symbol(0x0030, ":"),
			new Symbol(0x0031, "("),
			new Symbol(0x0032, ")"),
			new Symbol(0x0033, "->"),
			new Symbol(0x0034, "integer"),
			new Symbol(0x0035, "real"),
			new Symbol(0x0036, "boolean"),
			new Symbol(0x0037, "set"),
			new Symbol(0x0038, "element"),
			new Symbol(0x0039, "graph"),
			new Symbol(0x003A, "string"),
			new Symbol(0x003B, "=="),
			new Symbol(0x003C, "!="),
			new Symbol(0x003D, "or"),
			new Symbol(0x003E, "and"),
			new Symbol(0x003F, "not"),
			new Symbol(0x0040, "in"),
			new Symbol(0x0041, "subset"),
			new Symbol(0x0042, ">="),
			new Symbol(0x0043, ">"),
			new Symbol(0x0044, "<"),
			new Symbol(0x0045, "<="),
			new Symbol(0x0046, "+"),
			new Symbol(0x0047, "-"),
			new Symbol(0x0048, "*"),
			new Symbol(0x0049, "/"),
			new Symbol(0x004A, "mod"),
			new Symbol(0x004B, "^"),
			new Symbol(0x004C, "union"),
			new Symbol(0x004D, "intersection"),
			new Symbol(0x004E, ".V"),
			new Symbol(0x004F, ".E"),
			new Symbol(0x0050, ".src"),
			new Symbol(0x0051, ".dst"),
			new Symbol(0x0052, "true"),
			new Symbol(0x0053, "false") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public GrammarLexer(string input) : base(commonAutomaton, terminals, 0x000A, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public GrammarLexer(TextReader input) : base(commonAutomaton, terminals, 0x000A, input) {}
	}
}
