/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.5.1.0
 */

using System.CodeDom.Compiler;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace LexParserLib
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	[GeneratedCode("Hime.SDK", "3.5.1.0")]
	internal class GrammarLexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(GrammarLexer), "GrammarLexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		[GeneratedCode("Hime.SDK", "3.5.1.0")]
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal id
			/// </summary>
			public const int TerminalId = 0x0003;
			/// <summary>
			/// The unique identifier for terminal realNumber
			/// </summary>
			public const int TerminalRealNumber = 0x0004;
			/// <summary>
			/// The unique identifier for terminal integerNumber
			/// </summary>
			public const int TerminalIntegerNumber = 0x0005;
			/// <summary>
			/// The unique identifier for terminal WHITE_SPACE
			/// </summary>
			public const int TerminalWhiteSpace = 0x0006;
			/// <summary>
			/// The unique identifier for terminal SEPARATOR
			/// </summary>
			public const int TerminalSeparator = 0x0007;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		[GeneratedCode("Hime.SDK", "3.5.1.0")]
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0003, "id"),
			new Symbol(0x0004, "realNumber"),
			new Symbol(0x0005, "integerNumber"),
			new Symbol(0x0006, "WHITE_SPACE"),
			new Symbol(0x0007, "SEPARATOR"),
			new Symbol(0x0024, "export"),
			new Symbol(0x0025, "="),
			new Symbol(0x0026, "|"),
			new Symbol(0x0027, ","),
			new Symbol(0x0028, "_"),
			new Symbol(0x0029, "["),
			new Symbol(0x002A, "]"),
			new Symbol(0x002B, ":"),
			new Symbol(0x002C, "("),
			new Symbol(0x002D, ")"),
			new Symbol(0x002E, "->"),
			new Symbol(0x002F, "integer"),
			new Symbol(0x0030, "real"),
			new Symbol(0x0031, "boolean"),
			new Symbol(0x0032, "set"),
			new Symbol(0x0033, "element"),
			new Symbol(0x0034, "=="),
			new Symbol(0x0035, "!="),
			new Symbol(0x0036, "or"),
			new Symbol(0x0037, "and"),
			new Symbol(0x0038, "not"),
			new Symbol(0x0039, "in"),
			new Symbol(0x003A, "subset"),
			new Symbol(0x003B, ">="),
			new Symbol(0x003C, ">"),
			new Symbol(0x003D, "<"),
			new Symbol(0x003E, "<="),
			new Symbol(0x003F, "+"),
			new Symbol(0x0040, "-"),
			new Symbol(0x0041, "*"),
			new Symbol(0x0042, "/"),
			new Symbol(0x0043, "mod"),
			new Symbol(0x0044, "^"),
			new Symbol(0x0045, "union"),
			new Symbol(0x0046, "intersection"),
			new Symbol(0x0047, "{"),
			new Symbol(0x0048, "}"),
			new Symbol(0x0049, "true"),
			new Symbol(0x004A, "false") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public GrammarLexer(string input) : base(commonAutomaton, terminals, 0x0007, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public GrammarLexer(TextReader input) : base(commonAutomaton, terminals, 0x0007, input) {}
	}
}
